backend:
  name: github
  repo: DCCUProject5067/DCCUProject5067
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "movies"
    label: "Movies"
    folder: "movies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
